MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("sysu_train",)
  TEST: ("sysu_test","sysu_query",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 0
SOLVER:
  CHECKPOINT_PERIOD: 1500
  WEIGHT_DECAY: 0.0001
# gpu=1
#  BASE_LR: 0.02
#  STEPS: (60000, 80000)
#  MAX_ITER: 90000
# gpu=4
  BASE_LR: 0.01
  STEPS: (0, 15000, 20000)
  MAX_ITER: 30000

# config of reid model
REID:
  MODEL:
    PRETRAIN_PATH: '/home/hanchuchu/.torch/models/resnet50-19c8e357.pth'
  INPUT:
    SIZE_TRAIN: [384, 128]
    SIZE_TEST: [384, 128]
    PROB: 0.5 # random horizontal flip
    PADDING: 10
  DATASETS:
    NAMES: ('sysu')
    ID_NUM: 5532
  DATALOADER:
#    SAMPLER: 'softmax_triplet'
    SAMPLER: ['softmax','triplet']
    NUM_INSTANCE: 4
    NUM_WORKERS: 8
  SOLVER:
    OPTIMIZER_NAME: 'Adam'
    MAX_EPOCHS: 150
    BASE_LR: 0.00035
    BIAS_LR_FACTOR: 1
    WEIGHT_DECAY: 0.0005
    WEIGHT_DECAY_BIAS: 0.0005
    IMS_PER_BATCH: 64
    STEPS: [40, 70]
    GAMMA: 0.1
    WARMUP_FACTOR: 0.01
    WARMUP_ITERS: 10
    WARMUP_METHOD: 'linear'
    CHECKPOINT_PERIOD: 10
    LOG_PERIOD: 100
    EVAL_PERIOD: 10
  TEST:
    IMS_PER_BATCH: 256
    GALLERY_SIZE: 100
    WEIGHT: "/unsullied/sharefs/hanchuchu/isilon-home/train_log/mask/resnet50_model_150.pth"
  OUTPUT_DIR: "/unsullied/sharefs/hanchuchu/isilon-home/train_log/hccc"





















